/**
 * Sidebar for the `courses` docs instance (see the plugin entry in
 * docusaurus.config.js). Kept separate from sidebars.js so the course catalog
 * can be reorganised or versioned without touching the main site.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Generated from the courses-docs/ folder structure.
  coursesSidebar: [{type: 'autogenerated', dirName: '.'}],
};

module.exports = sidebars;
